/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rreports;

import reports.*;
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author acer
 */
public class rreport extends javax.swing.JInternalFrame {

    /**
     * Creates new form managepaartylist
     */
    public rreport() {
        initComponents();
            this.setBorder(javax.swing. BorderFactory.createEmptyBorder(0,0,0,0)); 
       BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
       bi.setNorthPane (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partylistpane = new javax.swing.JDesktopPane();
        topbar = new javax.swing.JPanel();
        tables = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout partylistpaneLayout = new javax.swing.GroupLayout(partylistpane);
        partylistpane.setLayout(partylistpaneLayout);
        partylistpaneLayout.setHorizontalGroup(
            partylistpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        partylistpaneLayout.setVerticalGroup(
            partylistpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(partylistpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 470));

        topbar.setBackground(new java.awt.Color(255, 255, 255));
        topbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tables.setForeground(new java.awt.Color(204, 0, 0));
        tables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tables.setText("Tables");
        tables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tablesMouseExited(evt);
            }
        });
        topbar.add(tables, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        getContentPane().add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 820, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesMouseClicked
        partylistpane.removeAll();
        tables vw = new tables();
        partylistpane.add(vw).setVisible(true);
    }//GEN-LAST:event_tablesMouseClicked

    private void tablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesMouseEntered
        tables.setOpaque(true);
        tables.setBackground(new java.awt.Color(204,204,204));
        tables.setForeground(Color.white);
    }//GEN-LAST:event_tablesMouseEntered

    private void tablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesMouseExited
        tables.setBackground(Color.white);
        tables.setForeground(new java.awt.Color(204,0,0));
        tables.setOpaque(false);
    }//GEN-LAST:event_tablesMouseExited

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        partylistpane.removeAll();
        pendinggs ad = new pendinggs();
        partylistpane.add(ad).setVisible(true);

    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane partylistpane;
    private javax.swing.JLabel tables;
    private javax.swing.JPanel topbar;
    // End of variables declaration//GEN-END:variables
}
