/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applications;

import static User.edituser.getHeightFromWidth;
import config.PanelPrinter;
import config.dbconnect;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class printapp extends javax.swing.JFrame {

    /**
     * Creates new form printapp
     */
    public printapp() {
        initComponents();
    }
          public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
          
          public static String status;
    
     public boolean getids(){ 
       dbconnect dbc = new dbconnect();
     try {    
             
        String queryPartylist = "SELECT * FROM applications WHERE aid = '" + id.getText() + "'";
        ResultSet rsPartylist = dbc.getData(queryPartylist);
        boolean valid = true;

        if (rsPartylist.next()) {
            status = rsPartylist.getString("status");
        } else {
            System.out.println(""+status);
            valid = false;
        }

       
        return valid;
        } catch (SQLException ex) {
            System.out.println(""+ex);
            return false;
        }    
    }      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Statement = new javax.swing.JLabel();
        Statement1 = new javax.swing.JLabel();
        Statement2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        cname = new javax.swing.JLabel();
        pname = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        scclogo = new javax.swing.JLabel();
        comeleclogo = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        print1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        coc.setBackground(new java.awt.Color(255, 255, 255));
        coc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        coc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REPUBLIC OF THE PHILIPPINES");
        coc.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 440, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CERTIFICATE OF CANDIDACY");
        coc.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 440, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Commission of Elections");
        coc.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 440, -1));
        coc.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 410, 20));

        jLabel5.setText("Official Statement:");
        coc.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 390, 20));

        jLabel6.setText("Candidate Name: ");
        coc.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, 20));

        jLabel7.setText("Position Filed for: ");
        coc.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, 20));

        jLabel8.setText("Political Partylist:");
        coc.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 90, 20));

        jLabel9.setText("Date Filed:");
        coc.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 70, 20));

        jLabel10.setText("Filing number:");
        coc.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 80, 20));

        Statement.setText("upcoming elections.");
        coc.add(Statement, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 390, 20));

        Statement1.setText("      This certifies that the individual named herein has officially filed a valid ");
        coc.add(Statement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 380, 20));

        Statement2.setText("Certificate of Candidacy and is recognized as a qualified candidate for the ");
        coc.add(Statement2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 380, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("This docuement is system-generated and does not require physical signature");
        coc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 350, 20));

        jLabel11.setText("      The filing has been accepted by the Election Administrator in complia");
        coc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 380, 20));

        jLabel12.setText("-nce with the rules set by the Commission on Elections.");
        coc.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 380, 20));

        jLabel13.setText("     This receipt confirms that all required documents have been submitted");
        coc.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 380, 20));

        jLabel14.setText(" and that the candidate’s name will appear on the official ballot, subject to ");
        coc.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 380, 20));
        coc.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 210, 20));
        coc.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 190, 20));
        coc.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 200, 20));
        coc.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 220, 20));
        coc.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 200, 20));

        jPanel2.setLayout(null);

        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(image);
        image.setBounds(0, 0, 90, 90);

        coc.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 90));
        coc.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 400, 20));

        jLabel15.setText("applicable laws and final verification.");
        coc.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 380, 20));

        scclogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scc80.jpg"))); // NOI18N
        coc.add(scclogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 110, 80));

        comeleclogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Comelec-Picsart-ImageResizer.png"))); // NOI18N
        coc.add(comeleclogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 80));

        print.setBackground(new java.awt.Color(204, 0, 0));
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("Print");
        print.setOpaque(true);
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });

        print1.setBackground(new java.awt.Color(204, 0, 0));
        print1.setForeground(new java.awt.Color(255, 255, 255));
        print1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print1.setText("Cancel");
        print1.setOpaque(true);
        print1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(print1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coc, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        if(getids()){
            if(!(status.equals("Qualified"))){
                JOptionPane.showMessageDialog(null, "Apllication not completed or disqualified, Cannot print application.!");
                id.setText("");
                cname.setText("");
                position.setText("");
                date.setText("");
                pname.setText("");
                this.dispose();
            }else{

                PanelPrinter pprint = new PanelPrinter(coc);
                pprint.printPanel();
            }
        }
    }//GEN-LAST:event_printMouseClicked

    private void print1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseClicked
       this.dispose();
    }//GEN-LAST:event_print1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Statement;
    private javax.swing.JLabel Statement1;
    private javax.swing.JLabel Statement2;
    public javax.swing.JLabel cname;
    public javax.swing.JPanel coc;
    public javax.swing.JLabel comeleclogo;
    public javax.swing.JLabel date;
    public javax.swing.JLabel id;
    public javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel pname;
    public javax.swing.JLabel position;
    private javax.swing.JLabel print;
    private javax.swing.JLabel print1;
    public javax.swing.JLabel scclogo;
    // End of variables declaration//GEN-END:variables
}
