/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Print;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author acer
 */
public class printing extends javax.swing.JInternalFrame {

    /**
     * Creates new form printing
     */
    public printing() {
        initComponents();
       this.setBorder(javax.swing. BorderFactory.createEmptyBorder(0,0,0,0)); 
       BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
       bi.setNorthPane (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prntcandidate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pending = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        printpane = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("  login/out");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 40));

        prntcandidate.setForeground(new java.awt.Color(204, 0, 0));
        prntcandidate.setText("  Print Candidate");
        prntcandidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prntcandidateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prntcandidateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prntcandidateMouseExited(evt);
            }
        });
        jPanel1.add(prntcandidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, 40));

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("  Print Partylist");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 100, 40));

        pending.setForeground(new java.awt.Color(204, 0, 0));
        pending.setText("  Pending User");
        pending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pendingMouseExited(evt);
            }
        });
        jPanel1.add(pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("  Log activities");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 510));

        javax.swing.GroupLayout printpaneLayout = new javax.swing.GroupLayout(printpane);
        printpane.setLayout(printpaneLayout);
        printpaneLayout.setHorizontalGroup(
            printpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        printpaneLayout.setVerticalGroup(
            printpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(printpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 700, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prntcandidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prntcandidateMouseClicked
       pcandidate pc = new pcandidate();
       printpane.removeAll();    
       printpane.add(pc).setVisible(true);
    }//GEN-LAST:event_prntcandidateMouseClicked

    private void pendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingMouseClicked
       pendinggs pnd = new pendinggs();
       printpane.removeAll();    
       printpane.add(pnd).setVisible(true);
    }//GEN-LAST:event_pendingMouseClicked

    private void pendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingMouseEntered
        pending.setOpaque(true);
        pending.setBackground(new java.awt.Color(221,21,21));
        pending.setForeground(Color.white);
    }//GEN-LAST:event_pendingMouseEntered

    private void pendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingMouseExited
        pending.setBackground(Color.white);
        pending.setForeground(new java.awt.Color(221,21,21));
        pending.setOpaque(false);
    }//GEN-LAST:event_pendingMouseExited

    private void prntcandidateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prntcandidateMouseEntered
        prntcandidate.setOpaque(true);
        prntcandidate.setBackground(new java.awt.Color(221,21,21));
        prntcandidate.setForeground(Color.white);
    }//GEN-LAST:event_prntcandidateMouseEntered

    private void prntcandidateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prntcandidateMouseExited
        prntcandidate.setBackground(Color.white);
        prntcandidate.setForeground(new java.awt.Color(221,21,21));
        prntcandidate.setOpaque(false);
    }//GEN-LAST:event_prntcandidateMouseExited

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       pendinggs pnd = new pendinggs();
       printpane.removeAll();    
       printpane.add(pnd).setVisible(true);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pending;
    private javax.swing.JDesktopPane printpane;
    private javax.swing.JLabel prntcandidate;
    // End of variables declaration//GEN-END:variables
}
